# Generated by Django 4.2.9 on 2024-09-27 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("layers", "0045_alter_dataset_abstract_en"),
        ("layers", "0047_auto_20240909_1236"),
    ]

    operations = []
