# Generated by Django 4.2.9 on 2024-11-05 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("layers", "0048_merge_20240927_1323"),
    ]

    operations = [
        migrations.AddField(
            model_name="attribute",
            name="attribute_unit",
            field=models.CharField(
                blank=True,
                help_text="the unit of the attribute (kg, °C, mm etc)",
                max_length=50,
                null=True,
                verbose_name="attribute unit",
            ),
        ),
    ]
