# Generated by Django 4.2.9 on 2024-11-07 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("layers", "0049_attribute_attribute_unit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attribute",
            name="attribute_unit",
            field=models.CharField(
                blank=True,
                help_text="the used unit for the attribute",
                max_length=50,
                null=True,
                verbose_name="attribute unit",
            ),
        ),
    ]
