# Generated by Django 4.2.17 on 2025-09-16 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("layers", "0051_alter_dataset_abstract_en_alter_dataset_purpose_en_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="attribute",
            name="attribute_method",
            field=models.CharField(
                blank=True,
                help_text="the used method for the attribute",
                max_length=2000,
                null=True,
                verbose_name="attribute method",
            ),
        ),
    ]
