# Generated by Django 4.2.17 on 2025-09-26 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("layers", "0051_alter_dataset_abstract_en_alter_dataset_purpose_en_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attribute",
            name="description",
            field=models.CharField(
                blank=True,
                help_text="description of attribute to be used in metadata",
                max_length=2048,
                null=True,
                verbose_name="attribute description",
            ),
        ),
    ]
