# Generated by Django 4.2.17 on 2025-09-26 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("layers", "0052_alter_attribute_description"),
        ("layers", "0052_attribute_attribute_method"),
    ]

    operations = []
