# Generated by Django 5.2.12 on 2026-04-09 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("layers", "0045_alter_attribute_id_alter_style_id"),
        ("layers", "0053_merge_20250926_1238"),
    ]

    operations = []
