# Generated by Django 4.2.30 on 2026-10-01 14:28

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LogoutEvent",
            fields=[
                (
                    "digest",
                    models.CharField(max_length=64, primary_key=True, serialize=False),
                ),
                ("issuer", models.CharField(max_length=512)),
                (
                    "subject",
                    models.CharField(blank=True, db_index=True, max_length=255),
                ),
                ("sid", models.CharField(blank=True, db_index=True, max_length=255)),
                ("issued_at", models.BigIntegerField()),
                ("received_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="SessionBinding",
            fields=[
                (
                    "session_key",
                    models.CharField(max_length=64, primary_key=True, serialize=False),
                ),
                ("issuer", models.CharField(max_length=512)),
                ("subject", models.CharField(db_index=True, max_length=255)),
                ("sid", models.CharField(db_index=True, max_length=255)),
                ("issued_at", models.BigIntegerField()),
                ("revoked", models.BooleanField(default=False)),
            ],
        ),
    ]
