# Generated by Django 5.2.12 on 2026-10-01 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("repository_sso", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sessionbinding",
            name="check_after",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="sessionbinding",
            name="id_token",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="sessionbinding",
            name="refresh_token",
            field=models.TextField(blank=True),
        ),
    ]
