# Generated by Django 5.2.12 on 2026-04-09 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0055_alter_serviceprofilerole_role"),
        ("services", "0056_alter_service_password_alter_service_username"),
    ]

    operations = []
