# Generated by Django 4.2.17 on 2025-12-04

from django.db import migrations, models
import django.db.models.deletion


def forwards_populate_organization(apps, schema_editor):
    Profile = apps.get_model("people", "Profile")
    Organization = apps.get_model("base", "Organization")
    db_alias = schema_editor.connection.alias

    profiles = (
        Profile.objects.using(db_alias)
        .exclude(organization_text__isnull=True)
        .exclude(organization_text__exact="")
    )

    for profile in profiles.iterator():
        raw_name = (profile.organization_text or "").strip()
        if not raw_name:
            continue

        organization = (
            Organization.objects.using(db_alias)
            .filter(organization__iexact=raw_name)
            .order_by("pk")
            .first()
        )
        if organization is None:
            organization = Organization.objects.using(db_alias).create(organization=raw_name)

        profile.organization = organization
        profile.save(update_fields=["organization"])


def backwards_populate_organization(apps, schema_editor):
    Profile = apps.get_model("people", "Profile")
    db_alias = schema_editor.connection.alias

    for profile in Profile.objects.using(db_alias).select_related("organization").iterator():
        organization = getattr(profile, "organization", None)
        profile.organization_text = organization.organization if organization else ""
        profile.save(update_fields=["organization_text"])


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0110_remove_resourcebase_date_collected_and_more"),
        ("people", "0032_profile_department_alter_profile_first_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="organization",
            new_name="organization_text",
        ),
        migrations.AddField(
            model_name="profile",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="name of the responsible organization",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="profiles",
                to="base.organization",
                verbose_name="Organization Name",
            ),
        ),
        migrations.RunPython(forwards_populate_organization, backwards_populate_organization, elidable=True),
        migrations.RemoveField(
            model_name="profile",
            name="organization_text",
        ),
    ]
