# Generated by Django 4.2.9 on 2024-12-03 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0036_merge_20210706_0951"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="department",
            field=models.CharField(
                blank=True,
                help_text="Department name or structural unit name of the responsible organization or individual",
                max_length=512,
                null=True,
                verbose_name="Department Name (Structural Unit)",
            ),
        ),
    ]
