# Generated by Django 3.2.23 on 2024-08-22 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0036_merge_20210706_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='organization',
            field=models.CharField(blank=True, choices=[('01', 'organization 01'), ('02', 'organization 02')], help_text='name of the responsible organization', max_length=255, null=True, verbose_name='Organization Name'),
        ),
    ]
