# Generated by Django 4.2.9 on 2024-12-05 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0038_migrate_sha1_passwords"),
    ]

    operations = [
        # department column already exists in DB from ZALF 4.4.3 migration —
        # update migration state only, skip DDL
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name="profile",
                    name="department",
                    field=models.CharField(
                        blank=True,
                        help_text="Department name or structural unit name of the responsible organization or individual",
                        max_length=512,
                        null=True,
                        verbose_name="Department Name (Structural Unit)",
                    ),
                ),
            ],
            database_operations=[],
        ),
        migrations.AlterField(
            model_name="profile",
            name="first_name",
            field=models.CharField(blank=True, max_length=150, verbose_name="first name"),
        ),
    ]
