# Generated by Django 4.2.9 on 2024-11-05 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("upload", "0039_auto_20220506_0833"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uploadparallelismlimit",
            name="max_number",
            field=models.PositiveSmallIntegerField(
                default=5, help_text="The maximum number of parallel uploads (0 to 32767)."
            ),
        ),
        migrations.AlterField(
            model_name="uploadsizelimit",
            name="max_size",
            field=models.PositiveBigIntegerField(
                default=104857600, help_text="The maximum file size allowed for upload (bytes)."
            ),
        ),
    ]
