# Generated by Django 4.2.17 on 2025-09-22 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("upload", "0042_alter_uploadparallelismlimit_max_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uploadparallelismlimit",
            name="max_number",
            field=models.PositiveSmallIntegerField(
                default=100, help_text="The maximum number of parallel uploads (0 to 32767)."
            ),
        ),
        migrations.AlterField(
            model_name="uploadsizelimit",
            name="max_size",
            field=models.PositiveBigIntegerField(
                default=5368709120, help_text="The maximum file size allowed for upload (bytes)."
            ),
        ),
    ]
