# Generated by Django 5.2.12 on 2026-04-09 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("upload", "0043_alter_uploadparallelismlimit_max_number_and_more"),
        ("upload", "0053_drop_celery_results_tables"),
    ]

    operations = []
