# Generated by Django 5.2.12 on 2026-05-06 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("upload", "0041_alter_uploadparallelismlimit_max_number_and_more"),
        ("upload", "0054_merge_20260409_0956"),
    ]

    operations = []
