# Generated by Django 5.2.12 on 2026-06-16 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("upload", "0055_merge_20260506_1124"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uploadparallelismlimit",
            name="max_number",
            field=models.PositiveSmallIntegerField(
                default=5, help_text="The maximum number of parallel uploads (0 to 32767)."
            ),
        ),
        migrations.AlterField(
            model_name="uploadsizelimit",
            name="max_size",
            field=models.PositiveBigIntegerField(
                default=104857600, help_text="The maximum file size allowed for upload (bytes)."
            ),
        ),
    ]
