# Generated by Django 5.2.12 on 2026-06-17 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("upload", "0056_alter_uploadparallelismlimit_max_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uploadparallelismlimit",
            name="max_number",
            field=models.PositiveSmallIntegerField(
                default=1000, help_text="The maximum number of parallel uploads (0 to 32767)."
            ),
        ),
    ]
