# Generated by Django 5.2.12 on 2026-08-14 13:21

from django.db import migrations, models

# UploadParallelismLimit.max_number defaults to settings.DEFAULT_MAX_PARALLEL_UPLOADS_PER_USER, so
# `makemigrations` detects a change whenever that environment variable differs from whatever was
# baked into the last migration -- 0057 recorded 1000, which matches no committed env file. The
# value below (100) is .env_test's, i.e. the one CI runs with, which keeps
# `makemigrations --check` deterministic there. Running makemigrations with a different .env will
# still report drift; that is inherited from upstream's settings-derived field default.
#
# The AlterField itself is inert: Django applies a column default during the ALTER and drops it
# again, so no existing database is affected by the number recorded here.


class Migration(migrations.Migration):

    dependencies = [
        ("upload", "0057_alter_uploadparallelismlimit_max_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uploadparallelismlimit",
            name="max_number",
            field=models.PositiveSmallIntegerField(
                default=100, help_text="The maximum number of parallel uploads (0 to 32767)."
            ),
        ),
    ]
