# Generated by Django 3.2.23 on 2024-03-15 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0096_merge_0088_auto_20231019_1244_0095_auto_20230331_0923'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resourcebase',
            name='use_constrains',
        ),
        migrations.AddField(
            model_name='resourcebase',
            name='use_constrains',
            field=models.ForeignKey(blank=True, help_text='license of the dataset', null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.restrictioncodetype', verbose_name='use_constrains'),
        ),
    ]
