# Generated by Django 4.2.9 on 2024-06-17 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0091_alter_hierarchicalkeyword_slug"),
        ("base", "0096_merge_0088_auto_20231019_1244_0095_auto_20230331_0923"),
    ]

    operations = []
