# Generated by Django 3.2.23 on 2024-03-15 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0097_auto_20240315_1232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resourcebase',
            name='restriction_code_type',
        ),
        migrations.AddField(
            model_name='resourcebase',
            name='restriction_code_type',
            field=models.ForeignKey(blank=True, help_text='license of the dataset', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restriction_code_type', to='base.restrictioncodetype', verbose_name='restrictions'),
        ),
        migrations.AlterField(
            model_name='resourcebase',
            name='use_constrains',
            field=models.ForeignKey(blank=True, help_text='license of the dataset', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='use_constrains', to='base.restrictioncodetype', verbose_name='use_constrains'),
        ),
    ]
