# Generated by Django 4.2.9 on 2024-07-17 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0091_alter_hierarchicalkeyword_slug"),
        ("base", "0097_resourcebase_metadata_license"),
    ]

    operations = []
