# Generated by Django 3.2.23 on 2024-08-22 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0098_auto_20240822_0831'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resourcebase',
            old_name='use_constraints',
            new_name='use_constrains',
        ),
    ]
