# Generated by Django 4.2.9 on 2024-09-24 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0091_alter_hierarchicalkeyword_slug"),
        ("base", "0100_auto_20240909_1236"),
    ]

    operations = []
