# Generated by Django 4.2.9 on 2024-12-03 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0101_merge_20240924_1415"),
    ]

    operations = [
        migrations.CreateModel(
            name="Funding",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "award_number",
                    models.CharField(
                        blank=True,
                        help_text="Award number or identifier for the funding",
                        max_length=255,
                        null=True,
                        verbose_name="Award Number",
                    ),
                ),
                (
                    "award_uri",
                    models.CharField(
                        blank=True,
                        help_text="The URI leading to a page provided by the funder for more information about the award (grant). (e.g. http://cordis.europa.eu/project/rcn/100180_en.html)",
                        max_length=255,
                        null=True,
                        verbose_name="Award URI",
                    ),
                ),
                (
                    "award_title",
                    models.CharField(
                        blank=True,
                        help_text="The human readable title of the award (grant). (e.g. MOTivational strength of ecosystem services)",
                        max_length=255,
                        null=True,
                        verbose_name="Award Title",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Organization",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "organization",
                    models.CharField(
                        blank=True,
                        help_text="Name of the Organization. (e.g. European Commission, Zurich University, ...)",
                        max_length=512,
                        null=True,
                        verbose_name="Name of the Institution",
                    ),
                ),
                (
                    "ror",
                    models.CharField(
                        blank=True,
                        help_text="Research Organization Registry (ROR) identifier of this organisation.",
                        max_length=255,
                        null=True,
                        verbose_name="Research Organization Registry",
                    ),
                ),
                (
                    "abbreviation",
                    models.CharField(
                        blank=True,
                        help_text="abbreviation of the Organisation (e.g. BMBF). Should come from ROR field other names.",
                        max_length=255,
                        null=True,
                        verbose_name="Abbreviation",
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="resourcebase",
            name="funders",
        ),
        migrations.DeleteModel(
            name="Funder",
        ),
        migrations.DeleteModel(
            name="FundingReference",
        ),
        migrations.AddField(
            model_name="funding",
            name="organization",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to="base.organization"
            ),
        ),
        migrations.AddField(
            model_name="resourcebase",
            name="fundings",
            field=models.ManyToManyField(
                blank=True,
                help_text="List of funders, funded dataset creators",
                null=True,
                to="base.funding",
                verbose_name="Fundings",
            ),
        ),
    ]
