# Generated by Django 4.2.9 on 2024-12-05 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0102_funding_organization_remove_resourcebase_funders_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactrole",
            name="role",
            field=models.CharField(
                choices=[
                    ("author", "party who authored the resource"),
                    (
                        "processor",
                        "party who has processed the data in a manner such that the resource has been modified",
                    ),
                    ("publisher", "party who published the resource"),
                    (
                        "custodian",
                        "party that accepts accountability and responsibility for the data and ensures         appropriate care and maintenance of the resource",
                    ),
                    (
                        "pointOfContact",
                        "party who can be contacted for acquiring knowledge about or acquisition of the resource",
                    ),
                    ("distributor", "party who distributes the resource"),
                    ("user", "party who uses the resource"),
                    ("resourceProvider", "party that supplies the resource"),
                    ("originator", "party who created the resource"),
                    ("owner", "party that owns the resource"),
                    (
                        "principalInvestigator",
                        "key party responsible for gathering information and conducting research",
                    ),
                    (
                        "dataCollector",
                        "Person/institution responsible for finding, gathering/collecting data under the guidelines of the au-thor(s) or Principal Investigator (PI).",
                    ),
                    (
                        "dataCurator",
                        "Person tasked with reviewing, enhancing, cleaning, or standardiz-ing metadata and the associated data submitted for storage, use, and maintenance within a data centre or repository.",
                    ),
                    ("editor", "A person who oversees the details related to the publication format of the resource."),
                    (
                        "hostingInstitution",
                        "Typically, the organisation allowing the resource to be available on the internet through the provision of its hardware/software/operating support.",
                    ),
                    (
                        "other",
                        "Any person or institution making a significant contribution to the development and/or maintenance of the resource, but whose contribution does not “fit” other con-trolled vocabulary for Type.",
                    ),
                    (
                        "producer",
                        "Typically a person or organisation responsible for the artistry and form of a media product.",
                    ),
                    (
                        "projectLeader",
                        "Person officially designated as head of project team or subproject team instrumental in the work necessary to development of the resource.",
                    ),
                    (
                        "projectManager",
                        "Person officially designated as manager of a project. Project may consist of one or many project teams and sub-teams.",
                    ),
                    ("projectMember", "Person on the membership list of a designated project/project team."),
                    (
                        "registrationAgency",
                        "Institution/organisation officially appointed by a Registration Authority to handle specific tasks within a defined area of responsibility.",
                    ),
                    (
                        "registrationAuthority",
                        "A standards-setting body from which Registration Agencies obtain official recognition and guidance.",
                    ),
                    (
                        "relatedPerson",
                        "A person without a specifically defined role in the development of the resource, but who is someone the author wishes to recognize.",
                    ),
                    (
                        "researchGroup",
                        "Typically refers to a group of indi-viduals with a lab, department, or division; the group has a particular, defined focus of activity.",
                    ),
                    (
                        "researcher",
                        "A person involved in analysing data or the results of an experiment or formal study. May indicate an intern or assistant to one of the authors who helped with research but who was not so “key” as to be listed as an author.",
                    ),
                    (
                        "rightsHolder",
                        "Person or institution owning or managing property rights, including intellectual property rights over the resource.",
                    ),
                    (
                        "sponsor",
                        "Person or organisation that issued a contract or under the auspices of which a work has been written, printed, published, developed, etc.",
                    ),
                    (
                        "supervisor",
                        "Designated administrator over one or more groups/teams working to produce a resource or over one or more steps of a development pro-cess.",
                    ),
                    (
                        "workPackageLeader",
                        "A Work Package is a recognized data product, not all of which is included in publication. The pack-age, instead, may include notes, discarded documents, etc. The Work Package Leader is responsi-ble for ensuring the comprehen-sive contents, versioning, and availability of the Work Package during the development of the resource.",
                    ),
                ],
                help_text="function performed by the responsible party",
                max_length=255,
            ),
        ),
    ]
