# Generated by Django 4.2.17 on 2025-07-24 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0092_migrate and_remove_resourcebase_files"),
        ("base", "0102_alter_resourcebase_abstract_and_more"),
    ]

    operations = []
