# Generated by Django 4.2.17 on 2025-07-28 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0103_merge_20250724_1222"),
        ("base", "0104_merge_20250725_0920"),
    ]

    operations = []
