# Generated by Django 4.2.17 on 2025-08-16 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0105_merge_20250728_0902"),
    ]

    operations = [
        migrations.AddField(
            model_name="resourcebase",
            name="data_lineage",
            field=models.TextField(
                blank=True,
                help_text="description of the lineage of the dataset, including its origin and history",
                max_length=1024,
                verbose_name="Data Lineage",
            ),
        ),
        migrations.AddField(
            model_name="resourcebase",
            name="metadata_lineage",
            field=models.TextField(
                blank=True,
                help_text="description of the lineage of the metadata, including its origin and history",
                null=True,
                verbose_name="Metadata Lineage",
            ),
        ),
        migrations.AlterField(
            model_name="resourcebase",
            name="edition",
            field=models.CharField(
                blank=True, help_text="version of the cited resource", max_length=255, null=True, verbose_name="Version"
            ),
        ),
        migrations.AlterField(
            model_name="resourcebase",
            name="restriction_other",
            field=models.ManyToManyField(
                blank=True,
                help_text="limitation(s) placed upon the access or use of the data by User. (Hold control to select more than one)",
                limit_choices_to=models.Q(("is_choice", True)),
                null=True,
                related_name="restriction_other",
                to="base.restrictioncodetype",
                verbose_name="Other Restrictions",
            ),
        ),
        migrations.AlterField(
            model_name="resourcebase",
            name="use_constraint_restrictions",
            field=models.ManyToManyField(
                blank=True,
                help_text="limitation(s) placed upon the access or use of the data by Admin. (Hold control to select more than one)",
                null=True,
                to="base.restrictioncodetype",
                verbose_name="Use Constraint Restrictions",
            ),
        ),
    ]
