# Generated by Django 4.2.17 on 2025-08-16 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0106_resourcebase_data_lineage_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="relatedidentifier",
            name="description",
            field=models.CharField(
                blank=True,
                help_text="Description of the related identifier",
                max_length=255,
                verbose_name="Related Identifier Description",
            ),
        ),
    ]
