# Generated by Django 4.2.17 on 2025-08-16 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0107_relatedidentifier_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="relatedproject",
            name="description",
            field=models.CharField(
                blank=True,
                help_text="Description of the related project",
                max_length=255,
                verbose_name="Related Project Description",
            ),
        ),
    ]
