# Generated by Django 4.2.17 on 2025-09-08 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0108_relatedproject_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resourcebase",
            name="conformity_explanation",
            field=models.CharField(
                blank=True,
                help_text="Give an Explanation about the conformity check. (e.g. See the referenced specification.)",
                max_length=4000,
                verbose_name="Conformity Explanation",
            ),
        ),
    ]
