# Generated by Django 4.2.17 on 2025-11-13 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0109_alter_resourcebase_conformity_explanation"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="resourcebase",
            name="date_collected",
        ),
        migrations.RemoveField(
            model_name="resourcebase",
            name="parent_identifier",
        ),
        migrations.AlterField(
            model_name="resourcebase",
            name="data_lineage",
            field=models.TextField(
                blank=True,
                help_text="description of the lineage of the dataset, including its origin and history",
                max_length=2048,
                verbose_name="Data Lineage",
            ),
        ),
        migrations.AlterField(
            model_name="resourcebase",
            name="metadata_lineage",
            field=models.TextField(
                blank=True,
                default="",
                help_text="description of the lineage of the metadata, including its origin and history",
                max_length=2048,
                verbose_name="Metadata Lineage",
            ),
            preserve_default=False,
        ),
    ]
