# Generated by Django 4.2.17 on 2026-01-29 13:28

from django.db import migrations, models


def set_initial_order(apps, schema_editor):
    """Set order=1 for all existing ContactRole entries."""
    ContactRole = apps.get_model("base", "ContactRole")
    ContactRole.objects.all().update(order=1)


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0110_remove_resourcebase_date_collected_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contactrole",
            options={"ordering": ("order", "id")},
        ),
        migrations.AddField(
            model_name="contactrole",
            name="order",
            field=models.IntegerField(default=0),
        ),
        migrations.RunPython(set_initial_order, reverse_code=migrations.RunPython.noop),
    ]
