# Generated by Django 4.2.17 on 2026-01-23 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0110_remove_resourcebase_date_collected_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contactrole",
            options={"ordering": ("order", "id")},
        ),
        migrations.AddField(
            model_name="contactrole",
            name="order",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
