# Generated by Django 4.2.17 on 2025-11-20 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0110_remove_resourcebase_date_collected_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ELTERHabitatType",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "habitat_code",
                    models.CharField(
                        help_text="eLTER Habitat Type code",
                        max_length=32,
                        unique=True,
                        verbose_name="eLTER Habitat Code",
                    ),
                ),
                (
                    "habitat_name",
                    models.CharField(
                        help_text="eLTER Habitat Type name",
                        max_length=255,
                        unique=True,
                        verbose_name="eLTER Habitat Name",
                    ),
                ),
                (
                    "habitat_description",
                    models.TextField(
                        help_text=("Description of the eLTER Habitat Type",), verbose_name="eLTER Habitat Description"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ELTERStandardObservations",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "so_id",
                    models.CharField(
                        help_text="eLTER Standard Observation ID", max_length=32, unique=True, verbose_name="SO ID"
                    ),
                ),
                (
                    "short_name",
                    models.CharField(
                        help_text="Short name of the eLTER Standard Observation",
                        max_length=255,
                        unique=True,
                        verbose_name="Short Name",
                    ),
                ),
                (
                    "long_name",
                    models.CharField(
                        help_text="Long name of the eLTER Standard Observation",
                        max_length=1024,
                        unique=True,
                        verbose_name="Long Name",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ELTERInformation",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "deims_id",
                    models.CharField(
                        blank=True,
                        help_text="eLTER DEIMS identifier for the research infrastructure or site associated with this resource",
                        max_length=255,
                        null=True,
                        verbose_name="DEIMS ID",
                    ),
                ),
                (
                    "habitats",
                    models.ForeignKey(
                        blank=True,
                        help_text="eLTER Habitat Types associated with this resource",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="base.elterhabitattype",
                    ),
                ),
                (
                    "standard_observation",
                    models.ForeignKey(
                        blank=True,
                        help_text="eLTER Standard Observation associated with this resource",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="base.elterstandardobservations",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="resourcebase",
            name="eLTER_information",
            field=models.ManyToManyField(
                blank=True,
                help_text="eLTER specific metadata information, https://elter-ri.eu/",
                null=True,
                related_name="eLTER_information",
                to="base.elterinformation",
                verbose_name="eLTER Information",
            ),
        ),
    ]
