# Generated by Django 4.2.17 on 2026-02-23 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0111_contactrole_position"),
        ("base", "0113_resourcetypegeneral_relatedidentifier_resource_type_general"),
    ]

    operations = []
