# Generated by Django 5.2.12 on 2026-04-09 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0095_alter_configuration_id_alter_contactrole_id_and_more"),
        ("base", "0113_resourcetypegeneral_relatedidentifier_resource_type_general"),
    ]

    operations = []
