# Generated by Django 4.2.17 on 2026-04-02 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0113_resourcetypegeneral_relatedidentifier_resource_type_general"),
    ]

    operations = [
        migrations.AddField(
            model_name="resourcebase",
            name="download_count",
            field=models.IntegerField(default=0),
        ),
    ]
