# Generated by Django 4.2.17 on 2026-02-27 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0111_contactrole_position"),
        ("base", "0114_merge_20260223_1444"),
    ]

    operations = []
