# Generated by Django 5.2.12 on 2026-05-06 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0114_merge_20260409_0956"),
        ("base", "0116_contactrole_position_default"),
    ]

    operations = []
