# Generated by Django 4.2.24 on 2026-04-01 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0094_fix_otherrestrictions_codetype"),
        ("base", "0116_contactrole_position_default"),
    ]

    operations = []
