# Generated by Django 5.2.12 on 2026-06-16 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0117_merge_20260506_1124"),
    ]

    operations = [
        migrations.AlterField(
            model_name="funding",
            name="id",
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
        migrations.AlterField(
            model_name="organization",
            name="id",
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
        migrations.AlterField(
            model_name="relatedidentifier",
            name="id",
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
        migrations.AlterField(
            model_name="relatedproject",
            name="id",
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
    ]
