# Generated by Django 5.2.12 on 2026-06-30 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0118_alter_funding_id_alter_organization_id_and_more"),
        ("base", "0118_merge_download_count"),
    ]

    operations = []
