# Generated by Django 5.2.9 on 2026-09-24 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0120_alter_contactrole_role_data_manager"),
    ]

    operations = [
        migrations.CreateModel(
            name="GeoKeyword",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("source", models.CharField(max_length=64)),
                ("level", models.PositiveSmallIntegerField()),
                ("layer_name", models.CharField(max_length=255)),
                ("gid", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "Geographic Keyword",
                "verbose_name_plural": "Geographic Keywords",
                "ordering": ("source", "level", "name"),
                "indexes": [
                    models.Index(fields=["source", "level"], name="base_geokey_source_level_idx"),
                    models.Index(fields=["gid"], name="base_geokey_gid_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("source", "gid"),
                        name="base_geokeyword_unique_source_gid",
                    )
                ],
            },
        ),
        migrations.AddField(
            model_name="resourcebase",
            name="geo_keywords",
            field=models.ManyToManyField(
                blank=True,
                help_text="Structured geographic identifiers associated with the resource",
                related_name="resources",
                to="base.geokeyword",
                verbose_name="Geographic Keywords",
            ),
        ),
    ]
