# Generated by Django 5.2.9 on 2026-09-24 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0121_resourcebase_geo_keywords"),
    ]

    operations = [
        migrations.CreateModel(
            name="ResearchDomain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                (
                    "description",
                    models.TextField(blank=True, default="", max_length=1000),
                ),
                ("order_id", models.PositiveIntegerField(db_index=True, default=0)),
            ],
            options={
                "verbose_name": "Research Domain",
                "verbose_name_plural": "Research Domains",
                "ordering": ("order_id", "name"),
            },
        ),
        migrations.AddField(
            model_name="resourcebase",
            name="research_domains",
            field=models.ManyToManyField(
                blank=True,
                help_text="Research disciplines associated with the resource",
                related_name="resources",
                to="base.researchdomain",
                verbose_name="Research Domains",
            ),
        ),
    ]
