# Generated by Django 5.2.12 on 2026-09-29 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0122_resourcebase_research_domains"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resourcebase",
            name="abstract",
            field=models.CharField(
                help_text="brief narrative summary of the content of the resource(s)",
                max_length=6000,
                verbose_name="Abstract (English)",
            ),
        ),
        migrations.AlterField(
            model_name="resourcebase",
            name="abstract_translated",
            field=models.TextField(
                help_text="brief german narrative summary of the content of the resource(s)",
                max_length=2000,
                verbose_name="Abstract (German)",
            ),
        ),
    ]
