# Generated by Django 5.2.12 on 2026-06-15 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zalf_cms", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="banner",
            name="link",
            field=models.CharField(
                blank=True, help_text="Supports internal paths like /catalogue/#/... and external URLs.", max_length=500
            ),
        ),
        migrations.AlterField(
            model_name="highlightcase",
            name="link",
            field=models.CharField(
                blank=True, help_text="Supports internal paths like /catalogue/#/... and external URLs.", max_length=500
            ),
        ),
    ]
