# Generated by Django 5.2.12 on 2026-06-15 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zalf_cms", "0002_alter_banner_link_alter_highlightcase_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="newspage",
            name="external_link",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="newspage",
            name="is_featured",
            field=models.BooleanField(default=False),
        ),
    ]
