# Generated by Django 5.2.12 on 2026-06-15 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailcore", "0094_alter_page_locale"),
        ("zalf_cms", "0004_alter_newspage_external_link"),
    ]

    operations = [
        migrations.CreateModel(
            name="NewsIndexPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("intro", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "News section",
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="TrainingIndexPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("intro", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Training section",
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="ZalfCmsSectionsPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("intro", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "ZALF CMS sections",
            },
            bases=("wagtailcore.page",),
        ),
    ]
