# Generated by Django 5.2.12 on 2026-06-15 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zalf_cms", "0005_newsindexpage_trainingindexpage_zalfcmssectionspage"),
    ]

    operations = [
        migrations.AddField(
            model_name="banner",
            name="button_label",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="banner",
            name="eyebrow",
            field=models.CharField(blank=True, max_length=160),
        ),
    ]
