# Generated by Django 5.2.12 on 2026-06-15 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailcore", "0094_alter_page_locale"),
        ("zalf_cms", "0006_banner_button_label_banner_eyebrow"),
    ]

    operations = [
        migrations.AddField(
            model_name="banner",
            name="target_page",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional CMS page opened when the banner CTA is clicked.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailcore.page",
            ),
        ),
        migrations.AlterField(
            model_name="banner",
            name="link",
            field=models.CharField(
                blank=True,
                help_text="Fallback link. Supports internal paths like /catalogue/#/... and external URLs.",
                max_length=500,
            ),
        ),
    ]
