# Generated by Django 5.2.12 on 2026-04-09 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("maps", "0044_alter_maplayer_id"),
        ("maps", "0047_alter_map_abstract_en_alter_map_purpose_en_and_more"),
    ]

    operations = []
