# Generated by Django 4.2.9 on 2024-11-28 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0041_auto_20240909_1236"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="abstract_en",
            field=models.CharField(
                help_text="brief narrative summary of the content of the resource(s)",
                max_length=6000,
                null=True,
                verbose_name="Abstract",
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="purpose_en",
            field=models.TextField(
                blank=True,
                help_text="summary of the intentions with which the resource(s) was developed",
                max_length=1024,
                null=True,
                verbose_name="Purpose",
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="title_en",
            field=models.CharField(
                help_text="name by which the cited resource is known", max_length=512, null=True, verbose_name="Title"
            ),
        ),
    ]
