# Generated by Django 5.2.12 on 2026-09-29 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0042_alter_document_abstract_en_alter_document_purpose_en_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="abstract_en",
            field=models.CharField(
                help_text="brief narrative summary of the content of the resource(s)",
                max_length=6000,
                null=True,
                verbose_name="Abstract (English)",
            ),
        ),
    ]
