name: "Code formatting"

on:
  push:
    branches: [ main ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ main ]

jobs:
  validate:

    strategy:
      fail-fast: false
      matrix:
        python-version: [ '3.12']

    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.user.login != 'dependabot[bot]'}}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python ${{matrix.python-version}}
      uses: actions/setup-python@v5
      with:
        python-version: ${{matrix.python-version}}

    - name: Install flake8 & black
      run: pip install flake8 black

    - name: "Check: flake8"
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 geonode --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 geonode --count --max-line-length=120 --exclude=geonode/*/migrations,geonode/*/settings.py,static,node_modules --ignore=E121,E122,E124,E126,E226 --statistics

    - name: "Check: black"
      run: black --check geonode
